repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.27.1
    hooks:
      - id: commitizen
        stages:
          - commit-msg
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/rtts/djhtml
    rev: "v1.5.0" # replace with the latest tag on GitHub
    hooks:
      - id: djhtml
        # Indent only HTML files in template directories
        files: .*/templates/.*\.html$
      - id: djcss
        # Run this hook only on SCSS files (CSS and SCSS is the default)
        types: [scss]
  # - id: djjs
  #   # Exclude JavaScript files in vendor directories
  #   exclude: .*/vendor/.*
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: "v8.10.0" # Use the sha / tag you want to point at
  #   hooks:
  #     - id: eslnt
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: "" # Use the sha / tag you want to point at
  #   hooks:
  #     - id: prettier
  # - id: typos
  #   name: typos
  #   description: Source code spell checker, binary install
  #   language: python
  #   entry: typos
  #   args: [--write-changes]
  #   types: [text]
  # - id: curlylint
  #   name: curlylint
  #   description: A linter which checks the indentation and the correctness of Jinja-like/HTML templates.
  #   language: python
  #   language_version: python3
  #   entry: curlylint
  #   files: '\.(html|jinja|twig)$'   -   id: check-added-large-files
